name: Upload Python Package

on: push
  # release:
  #   types: [created]

jobs:
#   print:
#     name: Hello World
#     runs-on: ubuntu-18.04
#     steps:
#       - name: Hello (.-.)
#         run: echo Hi
  deploy:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        python setup.py sdist bdist_wheel
    - name: Build and publish
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PYPI_USER_USERNAME }}
        password: ${{ secrets.PYPI_USER_PASSWORD }}

      # env:
      #   TWINE_USERNAME: ${{ secrets.PYPI_USER_USERNAME }}
      #   TWINE_PASSWORD: ${{ secrets.PYPI_USER_PASSWORD }}
      # run: |
      #   python setup.py sdist bdist_wheel
      #   twine upload dist/*

# github.event_name == 'push'


# name: Publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI

# on: push

# jobs:
#   build-n-publish:
#     name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI
#     runs-on: ubuntu-18.04

#     steps:
#     - uses: actions/checkout@master
#     - name: Set up Python 3.7
#       uses: actions/setup-python@v1
#       with:
#         python-version: 3.7
#     - name: Install pep517
#       run: >-
#         python -m
#         pip install
#         pep517
#         --user
#     - name: Build a binary wheel and a source tarball
#       run: >-
#         python -m
#         pep517.build
#         --source
#         --binary
#         --out-dir dist/
#     - name: Publish distribution ðŸ“¦ to Test PyPI
#       uses: pypa/gh-action-pypi-publish@master
#       with:
#         password: ${{ secrets.test_pypi_password }}
#         repository_url: https://test.pypi.org/test_pypi/
#     - name: Publish distribution ðŸ“¦ to PyPI
#       if: startsWith(github.event.ref, 'refs/tags')
#       uses: pypa/gh-action-pypi-publish@master
#       with:
#         password: ${{ secrets.pypi_password }}


