[tool.poetry]
name = "migrark"
version = "0.3.1"
description = "Migration Management Library"
authors = ["Esteban Echeverry <eecheverry@nubark.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
psycopg2 = "^2.8"

[tool.poetry.dev-dependencies]
mypy = "^0.720.0"
pytest-coverage = "^0.0.0"
pytest = "^5.1"
bump2version = "^0.5.11"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
