[tool.poetry]
name = "felixlib"
version = "0.0.1"
description = "felixlib"
authors = ["spectereye <spectereye@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.17"
flask = "^1.1"
wtforms = "^2.2"
psutil = "^5.6"
pywebview = "^3.1"
pywinauto = "^0.6.8"
xlwings = "^0.16.0"
colorama = "^0.4.1"
pywin32 = "^225.0"
send2trash = "^1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
